### ISSUE TITLE
Fix datetime of time range upper limit to include the whole day

### ISSUE THREAD

**Issue by souliane** [guludo/timewarrior-balance#3]
If I type `timew bal 2022-01-01 to 2022-03-09` or `timew bal 2022-01-01 to today` (today is 2022-03-09), it actually doesn't count 2022-03-09 and calculate the balance only until yesterday. I think that's a bug, instead of getting this:
```
Start: Sat Jan  1 00:00:00 2022
  End: Wed Mar  9 00:00:00 2022
````
I expect to get this:
```
Start: Sat Jan  1 00:00:00 2022
  End: Thu Mar 10 00:00:00 2022
```
or, if you prefer, this would also be OK:
```
Start: Sat Jan  1 00:00:00 2022
  End: Wed Mar  9 23:59:59 2022
````

**Comment by guludo** [comment]
Hi @souliane.

Thank you for your feedback!

Yes. I think the original behavior was a bit confusing and that kinda bothered me too. I just applied a set of patches that changes the default behavior so that the start datetime is rounded down and the end datetime is rounded up.

I'll keep this issue open so you can confirm if that solves this.

**Comment by souliane** [comment]
Works fine, thank you!
